# Generated by Django 5.1.1 on 2024-10-03 05:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_moviereview_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moviereview",
            unique_together={("title", "user")},
        ),
    ]
